#!/usr/bin/env node
/**
 * Writes env.js from environment variables so the app can use them without
 * committing secrets. Run before build/deploy or for local dev (with .env).
 *
 * Usage:
 *   SUPABASE_URL=https://xxx.supabase.co SUPABASE_ANON_KEY=eyJ... EDGE_FUNCTION_URL=https://xxx.supabase.co/functions/v1/register node scripts/inject-env.js
 * Or: node scripts/inject-env.js   (reads from .env if present, e.g. via dotenv)
 */

const fs = require("fs");
const path = require("path");

try {
  require("dotenv").config({ path: path.join(__dirname, "..", ".env") });
} catch (_) {}

const SUPABASE_URL = process.env.SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || "";
const SUPABASE_TABLE = process.env.SUPABASE_TABLE || "TS Pass Claims";
const EDGE_FUNCTION_URL = process.env.EDGE_FUNCTION_URL || "";

const out = `// Generated by scripts/inject-env.js — do not commit. Add env.js to .gitignore.
window.__ENV__ = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)},
  SUPABASE_TABLE: ${JSON.stringify(SUPABASE_TABLE)},
  EDGE_FUNCTION_URL: ${JSON.stringify(EDGE_FUNCTION_URL)}
};
`;

const outPath = path.join(__dirname, "..", "env.js");
fs.writeFileSync(outPath, out, "utf8");
console.log("Wrote env.js from environment variables.");
